import React from "react";
import { Helmet, HelmetProvider } from "react-helmet-async";

const PrivacyPolicy = () => {
  return (
    <HelmetProvider>
     <Helmet>
        <meta
          name="description"
          content="At Homefirst, we respect and protect your privacy. We collect your personal information during your visit to our site, and we will never sell your data to anyone."
        />
        <title>
        Privacy Policy | Homefirst
        </title>
      </Helmet>
    <div className="privacy-policy">
      <h3 className="">Privacy Policy</h3>
      <p className="minigray">Last Updated: February 20, 2020</p>
      <p className="minigray">
        We here at iconic.systems respect and are committed to protecting your
        privacy. We may collect personally identifiable information when you
        visit our site. We also automatically receive and record information on
        our server logs from your browser including your IP address, cookie
        information and the page(s) you visited. We will not sell your
        personally identifiable information to anyone.
      </p>
      <p className="minigray">
        This page informs you of our policies regarding the collection, use and
        disclosure of personal data gathered from this website. We use your data
        to provide and improve your experience while visiting our website. By
        using our website, you agree to the collection and use of information in
        accordance with this policy.
      </p>
      <hr />
      <h5>Definations</h5>
      <h6>Pesonal Data </h6>
      <p className="minigray">
        Personal Data means data about a living individual who can be identified
        from those data (or from those and other information either in our
        possession or likely to come into our possession).
      </p>
      <h6>Usage Data </h6>
      <p className="minigray">
        Usage Data is data collected automatically either generated by the use
        of the website or from the website infrastructure itself (for example,
        the duration of a page visit).
      </p>
      <h6>Cookies </h6>
      <p className="minigray">
        Cookies are small files stored on your device (computer or mobile
        device).
      </p>
      <hr />
      <h5>Types of Data Collected</h5>
      <h6>Pesonal Data</h6>
      <p className="minigray">
        While using our website, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you ("Personal Data"). Personally identifiable information may
        include, but is not limited to:
      </p>
      <ul>
        <li className="minigray">Email address</li>
        <li className="minigray">First name and last name</li>
        <li className="minigray">Phone number</li>
        <li className="minigray">Address, State, Province, ZIP/Postal code, City</li>
        <li className="minigray">
          Purchase history, financial information, billing information, and
          payment methods
        </li>
        <li className="minigray">Cookies and Usage Data</li>
      </ul>
      <p className="minigray">
        We may use your Personal Data to contact you with newsletters, marketing
        or promotional materials and other information that may be of interest
        to you. You may opt out of receiving any, or all, of these
        communications from us by following the unsubscribe link or the
        instructions provided in any email we send.
      </p>
      <h6>Usage Data</h6>
      <p className="minigray">
        We may also collect information on how the website is accessed and used
        ("Usage Data"). This Usage Data may include information such as your
        computer's Internet Protocol address (e.g. IP address), browser type,
        browser version, the pages of our website that you visit, the time and
        date of your visit, the time spent on those pages, unique device
        identifiers and other diagnostic data.
      </p>
      <h6>Tracking & Cookies Data</h6>
      <p className="minigray">
        We use cookies and similar tracking technologies to track the activity
        on our website and we hold certain information.
      </p>
      <p className="minigray">
        Cookies are files with a small amount of data which may include an
        anonymous unique identifier. Cookies are sent to your browser from a
        website and stored on your device. Other tracking technologies are also
        used such as beacons, tags and scripts to collect and track information
        and to improve and analyze our website.
      </p>
      <p className="minigray">
        You can instruct your browser to refuse all cookies or to indicate when
        a cookie is being sent. However, if you do not accept cookies, you may
        not be able to use some portions of our website.
      </p>
      <h6>Examples of Cookies we use:</h6>
      <ul>
        <li className="minigray">Session Cookies: We use Session Cookies to operate our website.</li>
        <li className="minigray">
          Preference Cookies: We use Preference Cookies to remember your
          preferences and various settings.
        </li>
        <li className="minigray">
          Security Cookies: We use Security Cookies for security purposes.
        </li>
      </ul>
      <hr />
      <h5>Use of Data</h5>
      <h6>We use the collected data for various purposes:</h6>
      <ul>
        <li className="minigray">To provide and maintain our website</li>
        <li className="minigray">To notify you about changes to our website</li>
        <li className="minigray">
          To allow you to participate in interactive features of our website
          when you choose to do so
        </li>
        <li className="minigray">To provide customer support</li>
        <li className="minigray">
          To gather analysis or valuable information so that we can improve our
          website
        </li>
        <li className="minigray">To monitor the usage of our website</li>
        <li className="minigray">To detect, prevent and address technical issues</li>
        <li className="minigray">
          To provide you with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or inquired about unless you
          have opted not to receive such information
        </li>
      </ul>
      <hr />
      <h5>Disclosure of Data</h5>
      <h6>Disclosure for Law Enforcement</h6>
      <p className="minigray">
        Under certain circumstances, we may be required to disclose your
        Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g., a court or a government agency).
      </p>
      <hr />
      <h5>Security of Data</h5>
      <p className="minigray">
        The security of your data is important to us but remember that no method
        of transmission over the Internet or method of electronic storage is
        100% secure. While we strive to use commercially acceptable means to
        protect your Personal Data, we cannot guarantee its absolute security.
      </p>
      <hr />
      <h5>
        Our Policy on "Do Not Track" Signals under the California Online Privacy
        Protection Act (CalOPPA)
      </h5>
      <p className="minigray">
        We do not support Do Not Track ("DNT"). Do Not Track is a preference you
        can set in your web browser to inform websites that you do not want to
        be tracked.
      </p>
      <p className="minigray">
        You can enable or disable Do Not Track by visiting the Preferences or
        Settings page of your web browser.
      </p>
      <hr />
      <h5>Payments</h5>
      <p className="minigray">
        We may provide paid products and/or services within the website. In that
        case, we use third-party services for payment processing (e.g., payment
        processors).
      </p>
      <p className="minigray">
        We will not store or collect your payment card details. That information
        is provided directly to our third-party payment processors whose use of
        your personal information is governed by their Privacy Policy. These
        payment processors adhere to the standards set by PCI-DSS (Payment Card
        Industry Data Security Standard) as managed by the PCI Security
        Standards Council, which is a joint effort of brands like Visa,
        MasterCard, American Express and Discover. PCI-DSS requirements help
        ensure the secure handling of payment information.
      </p>
      <p className="minigray">The payment processors we work with are:</p>
      <h6>PayPal / Braintree</h6>
      <p className="minigray">
        Their Privacy Policy can be viewed at{" "}
        <a target="_blank" rel="noreferrer" href="https://www.paypal.com/webapps/mpp/ua/privacy-full">here</a>
      </p>
      <h6>Authorize.net</h6>
      <p className="minigray">
        Their Privacy Policy can be viewed at{" "}
        <a target="_blank" rel="noreferrer" href="https://usa.visa.com/legal/privacy-policy.html.html">here</a>
      </p>
      <hr />
      <h5>Third-Party Services</h5>
      <p className="minigray">
        We rely on third-party vendors for services and products that maintain
        and improve our website and the consumer shopping experience on our
        website. These third parties may provide us information such as location
        or demographic data, and our website may contain links to the websites
        or services of third parties. We are held to the privacy policies of
        these third parties, though we are not responsible for their privacy
        policies. We encourage all our site visitors to explore these
        third-party privacy policies by visiting their websites.
      </p>
      <hr />
      <h5>Links to Other Sites</h5>
      <p className="minigray">
        Our website may contain links to other sites that are not operated by
        us. If you click a third-party link, you will be directed to that
        third-party's site. We strongly advise you to review the Privacy Policy
        of every site you visit.
      </p>
      <p className="minigray">
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third-party sites or services.
      </p>
      <hr />
      <h5>Analytics</h5>
      <p className="minigray">
        We may use third-party Service Providers to monitor and analyze the use
        of our website.
      </p>
      <h6>Google Analytics</h6>
      <p className="minigray">
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third-party sites or services.
      </p>
      <p className="minigray">
        Google Analytics is a web analytics service offered by Google that
        tracks and reports website traffic. Google uses the data collected to
        track and monitor the use of our website. This data is shared with other
        Google services. Google may use the collected data to contextualise and
        personalise the ads of its own advertising network.
      </p>
      <p className="minigray">
        You can opt out of having made your activity on our website available to
        Google Analytics by installing the Google Analytics opt-out browser
        add-on. The add-on prevents the Google Analytics JavaScript (ga.js,
        analytics.js and dc.js) from sharing information with Google Analytics
        about visits activity.
      </p>
      <p className="minigray">
        For more information on the privacy practices of Google, please visit
        the{" "}
        <a target="_blank" rel="noreferrer" href="https://policies.google.com/privacy?hl=en">
          {" "}
          Google Privacy & Terms web page
        </a>
      </p>
      <hr />
      <h5>Google Ads</h5>
      <p className="minigray">
        When you visit our site, we collect personally identifiable information
        (PII) such as your email address and web behavior. We also automatically
        receive and record information on our server logs from your browser,
        including your IP address, cookie information and the page(s) you
        visited in order to serve you ads more relevant to your interests.
      </p>
      <p className="minigray">
        We will not sell your personally identifiable information to anyone. We
        will not send Google your precise geographic location without your
        consent.
      </p>
      <p className="minigray">
        We use pixels and cookies for remarketing activities across websites.
        Cookies are small files saved to your device that store preferences and
        information such as how you interact with websites and mobile
        applications, or apps. Google and Google partners can then display ads
        to you based off the web pages you visit and the ways in which you
        interact with those pages.
      </p>
      <p className="minigray">
        This means that our ads that you might see on third-party websites or
        Google partner sites are influenced by what you engage with on our site.
      </p>
      <p className="minigray">
        Visit{" "}
        <a target="_blank" rel="noreferrer" href="https://support.google.com/My-Ad-Center-Help/answer/12155451?hl=en-GB&visit_id=638110160322059426-157088526&rd=1">
          Google’s Ads Settings page
        </a>{" "}
        to opt out of Google’s use of cookies, to control the information that’s
        used to show you ads, and to personalize ads to your preferences. Visit
        the{" "}
        <a target="_blank" rel="noreferrer" href="https://optout.networkadvertising.org/?c=1">
          Network Advertising Initiative{" "}
        </a>
        to opt out of third-party vendors’ use of cookies.
      </p>
      <hr />
      <h5>Children's Privacy</h5>
      <p className="minigray">
        Our Service does not address anyone under the age of 18 ("Children").
      </p>
      <p className="minigray">
        We do not knowingly collect personally identifiable information from
        anyone under the age of 18. If you are a parent or guardian and you are
        aware that your Child has provided us with Personal Data, please contact
        us. If we become aware that we have collected Personal Data from
        Children without verification of parental consent, we take steps to
        remove that information from our servers.
      </p>
      <hr />
      <h5>Changes to This Privacy Policy</h5>
      <p className="minigray">
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p className="minigray">
        We will let you know via email and/or a prominent notice on our website
        prior to the change becoming effective and update the "effective date"
        at the top of this Privacy Policy.
      </p>
      <p className="minigray">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <hr />
      <h5>Contact Us</h5>
      <p className="minigray">
        If you have any questions about this Privacy Policy, please{" "}
        <a href="/contact-us">contact us</a>.
      </p>
    </div>
    </HelmetProvider>
  );
};

export default PrivacyPolicy;
